CREATE TABLE entities (
  entity_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id INTEGER REFERENCES clients(client_id) ON DELETE CASCADE NOT NULL,
  legal_name TEXT NOT NULL,
  ein VARCHAR(10) DEFAULT '00-0000000' NOT NULL,
  filer BOOLEAN NOT NULL,
  entity_type entity_types NOT NULL,
  active BOOLEAN NOT NULL
);

-- CREATE TABLE parent_to_sub (
--   parent_to_sub_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--   filing_year_id INTEGER REFERENCES filing_years(filing_year_id) NOT NULL,
--   parent_id INTEGER REFERENCES entities(entity_id) NOT NULL,
--   sub_id INTEGER REFERENCES entities(entity_id) NOT NULL
-- );