CREATE TABLE extensions (
  extension_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  engagement_id INTEGER REFERENCES engagements(engagement_id) ON DELETE CASCADE NOT NULL,
  entity_id INTEGER REFERENCES entities(entity_id) ON DELETE CASCADE NOT NULL,
  jurisdiction_id VARCHAR(7) NOT NULL,
  form_name VARCHAR(20) NOT NULL,
  due_date DATE NOT NULL,
  completion_status status_types NOT NULL
);

CREATE TABLE tax_returns (
  tax_return_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  engagement_id INTEGER REFERENCES engagements(engagement_id) ON DELETE CASCADE NOT NULL,
  entity_id INTEGER REFERENCES entities(entity_id) ON DELETE CASCADE NOT NULL,
  jurisdiction_id VARCHAR(7) NOT NULL,
  form_name VARCHAR(20) NOT NULL,
  extended BOOLEAN DEFAULT 'false' NOT NULL,
  due_date DATE NOT NULL,
  extended_due_date DATE NOT NULL,
  completion_status status_types NOT NULL
);