CREATE TABLE state_extensions (
  extension_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  engagement_id INTEGER REFERENCES engagements(engagement_id) ON DELETE CASCADE NOT NULL,
  entity_id INTEGER REFERENCES entities(entity_id) ON DELETE CASCADE NOT NULL,
  state_id VARCHAR(2) NOT NULL,
  form_name VARCHAR(20) NOT NULL,
  due_date DATE NOT NULL,
  extension_status status_types NOT NULL
);

CREATE TABLE state_tax_returns (
  state_tax_return_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  engagement_id INTEGER REFERENCES engagements(engagement_id) ON DELETE CASCADE NOT NULL,
  entity_id INTEGER REFERENCES entities(entity_id) ON DELETE CASCADE NOT NULL,
  state_id VARCHAR(2) NOT NULL,
  form_name VARCHAR(20) NOT NULL,
  extended BOOLEAN DEFAULT 'false' NOT NULL,
  due_date DATE NOT NULL,
  extended_due_date DATE NOT NULL,
  tax_return_status status_types NOT NULL
);